### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by amiltonwong** [nintendops/EPN_PointCloud#2]
Hi, @nintendops ,

When will the code be released?

Thanks~

**Comment by nintendops** [comment]
Hi @amiltonwong ,

I will find a day or two this month or in July to finish the final release. For now, the source code is available in the beta branch but they are not well documented and may need some fixes to the code structure. If you want to use it you may first need to write a setup.py to compile the cuda codes in vgtk/cuda. The final release will restructure the code in this branch and also will include links to download the datasets used in the experiments, as well as several pretrained checkpoints

**Comment by amiltonwong** [comment]
Thanks @nintendops !
