### ISSUE TITLE
Issues of Equivariant KPconv

### ISSUE THREAD

**Issue by JudgeLJX** [nintendops/EPN_PointCloud#4]
Hello,

Thanks for your contribution.

I have an issue:

How did you convert the kpconv to an equivariant version, is there any changes you made to their structure besides the quaternion representation?

Best Regards,

Judge

**Comment by nintendops** [comment]
Hi Judge,

we convert kpconv to the rotationally equivariant version by rotating the "kernel points" X times and extracting these rotated features into an extra dimensions. Please refer to the paper for the details.
