### ISSUE TITLE
Getting the equivariant representation

### ISSUE THREAD

**Issue by DubiousCactus** [nintendops/EPN_PointCloud#5]
Thank you for providing the code, great work!

I'm a bit confused by all the provided output blocks though... How could I get the equivariant features of an input pointcloud?
I'm thinking of modifying `RelSO3OutBlockR` and instead of
```python
        attention_wts = self.attention_layer(x_out).view(nb, na, na)
        confidence = F.softmax(attention_wts * self.temperature, dim=1)
        y = self.regressor_layer(x_out)

        # return: [nb, na, na], [nb, n_out, na, na]
        return confidence, y
```
do
```python
        attention_wts = self.attention_layer(x_out).view(nb, na, na)
        embedding = attention_wts @ x_out # Something of that sort (maybe with torch.einsum)
        return self.output_layer(embedding) # To get something like (batch_size, output_dim)
```

Is there a more straightforward way? Thanks.

**Comment by nintendops** [comment]
Any intermediate feature (e.g. x_out) will be in the equivariant representations. In this case you just need the x_out (probably of shape B, C, A with A being # of anchors without multiplying the attention weights, unless you also want to pay specific attentions to a certain anchors
